### ISSUE TITLE
seems to be broken in 19.09 :(

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/shared-data#4]
as seen here: https://build.galaxyproject.eu/job/usegalaxy-eu/job/shared-data/31/console

**Comment by bgruening** [comment]
@martenson have you seen any problem with library uploads in 19.09? Especially, when using ephemeris?

**Comment by hexylena** [comment]
Some number of those is normal? 

https://build.galaxyproject.eu/job/usegalaxy-eu/job/shared-data/30/console
https://build.galaxyproject.eu/job/usegalaxy-eu/job/shared-data/28/console

Usually it's because of the wrong extension in the data library.yml files in the training material.

**Comment by martenson** [comment]
@bgruening I am not aware of any, or related changes :/

**Comment by martenson** [comment]
I am now, xref: https://github.com/galaxyproject/galaxy/issues/8820

**Comment by hexylena** [comment]
I never reported this upstream because it never felt like a galaxy error, I was specifying incorrect yaml (unknown datatypes), and so galaxy refused to upload it. Seemed fine to me. Thanks @abretaud for fixing the library yamls!

**Comment by martenson** [comment]
In my book this has been fixed as of https://github.com/galaxyproject/galaxy/issues/8820, please close.
